# Generated by Django 3.1.3 on 2020-12-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
